theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端开发工程师

# 对你自己的简洁描述
description: 热爱未知，审美在线，愿意学习，激情运动

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: 嚣张(Victor Zhang)

# 你的联系方式
phone: 176******11

# 你的邮箱
email: victor0807@foxmail.com

# 你目前的住址
address: 山西吕梁

# 你毕业院校
school: 齐鲁工业大学

# 你的专业
profession: 过程装备与控制工程

# 你的学位
degree: 本科没毕业

# 你获得过的证书或奖励
credential: 中国机器人大赛三等奖/英语四级/计算机二级
